src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }
}

templates/base.html.twig
{% set route_name = app.request.attributes.get('_route') %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Accueil Espace Balades{% endblock %}
		</title>
		{{ encore_entry_link_tags('app') }}
		{% block stylesheets %}{% endblock %}
		<link rel="shortcut icon" href="#">
	</head>

	<body>
		<header id="header" class="bg-white shadow px-3 py-1 mb-4 rounded d-print-none">
			<div class="container">
				<div class="row">
					<nav class="col navbar navbar-expand-md navbar-light">
						<a
							class="navbar-brand" href="">
							{# {{ path('balades') }} à remplacer quand créée #}
							<img src="{{ asset('/img/image1.png')}}" width="100px" alt="Logo - Redirige vers l'accueil (liste des balades)" loading="lazy">
						</a>
						{# width du svg à régler en fonction de la taille d'écran - 120 = PC ; rien = mobile #}

						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>

						<div id="navbarNav" class="collapse navbar-collapse offset-md-7">
							<ul class="navbar-nav">
								{% if route_name != "login" %}
									<li class="nav-item dropdown d-md-block d-none">
									

										<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% if app.user %}{{ app.user.nom }}{% endif %}</a>
									
										
										<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
											
											<a class="dropdown-item" href="{{ path('app_logout') }}">Déconnexion</a>
										</div>
									</li>
									
									{# {{ path(profil) }} #}

									<li class="nav-item">
									{% if app.user %}
										<h2 class="my-4 text-center d-md-none">{{ app.user.nom }}</h2>
									{% endif %}
									</li>

									<hr class="dropdown-divider my-4 my-md-0 d-md-none">
									<li {% if route_name == "balade_index" %} class="nav-item active" {% else %} class="nav-item" {% endif %} >
										<a href="{{ path('balade_index') }}" class="nav-link">Les Balades</a>
									</li>
									<li {% if route_name == "checklist" %} class="nav-item active" {% else %} class="nav-item" {% endif %} >
										<a href="{{ path('checklist') }}" class="nav-link">La Checklist</a>
									</li>

									<li class="nav-item">
										<a class="nav-link mt-4 d-md-none" href="{{ path('app_logout') }}">Déconnexion</a>
									</li>
								{% endif %}
							</ul>
						</div>
						{# #navbarNav #}
					</nav>
				</div>
				{# .row #}
			</div>
			{# .container #}
		</header>
		{# .bg-dark #}


		<main id="main">
			{% block main %}{% endblock %}
		</main>


		<footer id="footer" class="bg-light py-4 mt-4 d-print-none">
			<div class="container">
				<div class="row">
					<div class="col text-md-center font-weight-bold">
						<a href="{{ path('balade_index') }}" class="text-secondary">Espace Balades</a>
					</div>
					{# .col #}

					<div class="col text-center font-weight-bold">
						<a href="{{ path('checklist') }}" class="text-secondary">Checklist</a>
					</div>
					{# .col #}
				</div>
				{# .row #}
			</div>
			{# .container #}
		</footer>

		{# JAVASCRIPT #}
		{{ encore_entry_script_tags('app') }}
		{% block javascripts %}{% endblock %}
	</body>
</html>